version: "2.1"
services:
  dev:
    image: radio_app
    build: .
    environment:
      PORT: 3000
    command:
      - npm
      - run
      - dev
    volumes:
      - .:/radio-app
      - node_modules:/radio-app/node_modules
    ports:
      - 3000:3000
  test:
    image: radio_app
    build: .
    command:
      - npm
      - run
      - test
    volumes:
      - .:/radio-app
      - node_modules:/radio-app/node_modules
  test-watch:
    image: radio_app
    build: .
    command:
      - npm
      - run
      - test:watch
    volumes:
      - .:/radio-app
      - node_modules:/radio-app/node_modules
  test-coverage:
    image: radio_app
    build: .
    command:
      - npm
      - run
      - test:coverage
    volumes:
      - .:/radio-app
      - node_modules:/radio-app/node_modules
volumes:
  node_modules: {}
